### ISSUE TITLE
COBWEB -- abstract all editor-related calls to the new /editors/ API

### ISSUE THREAD

**Issue by xmichael** [edina/fieldtrip-open#67]
Currently FTOpen does not use the /surveys/ API except for fetching the survey names of the **public** surveys. The new API needs to be used for accessing **all** survey editor files and names as there are important abstractions that need more than direct filesystem access. (e.g. using other user's surveys, publishing a survey) 

Current Action:
 - Keep AT as it is, i.e. using the EDINA version of the /editors/ API
 - Likewise, keep FTOpen public survey access as it is, i.e. using /editors/ API
 - Change FTOpen **registered** survey access to use /surveys/ instead of the low level /fs/ API to i) get all surveys and their properties and ii) to get the content of the survey (editor) file.

##The new API is as follows:

### Get all editors (surveys) IDs and their names (titles)

`GET /surveys/local/UUID/`
returns:

```json
{
"metadata": [ "b29c63ae-adc6-4732-8c6d-124c28e2659e", "c8942133-22ce-4f93-a90e-03ea02133d46" ],
"names": ["Another Woodlands Survey", "Grassland survey"]
 }
```

### Get a specific survey -- returns the contents of the editor file

`GET /surveys/local/UUID/SURVEYID`

NOTE: SURVEYID is basically the editor filename *without* the `.edtr` extension.

 
NOTE: The new API was initially /editors/ but renamed to /surveys/ for more compicated survey managed with groups etc. The old EDINA /editors/ API remains (deprecated) to ease migration and for backwards compatibility in case we missed something.

**Comment by panterz** [comment]
It's working now.
